language: node_js
node_js:
- node
cache:
  yarn: true
notifications:
  slack:
    secure: FN0Bq4ZZ6XL1p0Xht+8l92YRvFsuh/EkXr6LbrhiH2hubDb9CnLOEQi71CiAjpr/Jbc2E20JFNwCMlWsfGOmBMJCAYWO70MOZ9ud42hC7ZaN49qmT4NOcyARrYRcobX5WKiUV1klMdeSOZJ36Hn5NP0JRRMcs08U8zzfV8Xb3drkKqz1D2O89f3QgWGvEUaAgTqfjXb61KP98yF34KAIucPPBVVygxdM99PhanTFu2k3fwgsxyMMA4/wshQaxVDyzvdnn4g3Kk5cykjuxSTGxIU9o90/KIeDbwm2wDD2e1El5zpproKcnn9byCyuwacMkwmgfy3ZhJxa5urLXHULfIxDXIoLsaHHblDOxIaayqcEPzqEebrgWm+SUQklFtoXXYbkIXwoQMT16+QeK1hQEYedFT/+gneOKuTgh5h69jmMnC+uR97QmG5qhR4fo6qT64QFLmIsFwlRX0enwnE1ZKIqY6Lj3pXWqjp6C5DpHWL4+lzJr1qwkQ37Ft7go/bojYZBKpzi8Oz0LirLH22MBe4KAHEoaBB2Q/SL8vUlUM9en5BUVfv/vz+mb/S0MiaUcViK3oufIFeA0XWfUrONiqDZ6b7IB8nWdA+LmpymfJMXWrNM0mwIFAaZpPxwmIJyIB46ERWTyxlEceS15cb5sCjSBD05cCRpsdtAqh6heEc=
