version: 2.1
executors:
    default:
        docker:
            - image: cimg/node:18.20-browsers
        working_directory: ~/project
orbs:
    browser-tools: circleci/browser-tools@1.1.0
    slack: circleci/slack@4.2.0
jobs:
    build:
        executor: default
        steps:
            - browser-tools/install-chrome
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages2-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command:
                      yarn install --frozen-lockfile --cache-folder
                      ~/.cache/yarn
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages2-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Build
                  command: yarn build
            - run:
                  name: Test
                  command: yarn test
            - add_ssh_keys:
                  fingerprints:
                      - '5b:ea:d0:98:40:17:7b:c8:0a:fa:44:7a:84:a9:85:0d'
            - run:
                  name: Add Known Host
                  command:
                      mkdir -p ~/.ssh && echo "${REMOTE_HOSTKEY}" >>
                      ~/.ssh/known_hosts
            - run:
                  name: Install rsync
                  command: sudo apt-get update && sudo apt-get install rsync
            - run:
                  name: Deploy
                  command: ./deploy.sh
            - slack/notify:
                  channel: circleci
                  event: fail
                  template: basic_fail_1
                  mentions: '@ajsutton'
                  tag_pattern: '.*'
            - slack/notify:
                  channel: circleci
                  event: pass
                  template: success_tagged_deploy_1
                  tag_pattern: '.*'
workflows:
    build:
        jobs:
            - build
